import lxml.html
from selenium import webdriver
import time
import pandas as pd
import re

lst1 = []
lst2 = []
lst3 = []

def openBrowser():

    browser = webdriver.Chrome('/Users/harukisonehara/PycharmProjects/vertica/MIT/chromedriver')
    url = "https://mitsloan.onlinecampus.getsmarter.com/login/index.php"
    browser.get(url) #navigate to the page
    time.sleep(3)
    username = browser.find_element_by_id("username") #username form field
    password = browser.find_element_by_id("password") #password form field

    username.send_keys("nuovissimo@gmail.com")
    password.send_keys("harumiwa0608")

    submitButton = browser.find_element_by_id("loginbtn")
    #button.click()
    submitButton.click()
    time.sleep(5)
    showAll = "https://mitsloan.onlinecampus.getsmarter.com/user/index.php?contextid=739&roleid=0&id=4&perpage=5000&search=&mode=1"

    return browser, showAll

def profileSum():

    browser, showAll = openBrowser()

    browser.get(showAll)
    name = browser.find_elements_by_class_name("username")
    email = browser.find_elements_by_class_name("info")

    for el1, el2 in zip(name,email):
        lst1.append([el1.text,el2.text])


    for x in range(0, len(lst1)):
        extract = re.findall(r'[a-zA-Z0-9_.+-]+\@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+', lst1[x][1], re.MULTILINE)
        lst1[x][1] = extract

    for i in range(0, len(lst1)):

        if len(lst1[i][1]) != 0:
            getEmail = lst1[i][1][0]
            lst1[i].append(getEmail)
            del lst1[i][1]

        elif len(lst1[i][1]) == 0:
            lst1[i].append("none")
            del lst1[i][1]

    df = pd.DataFrame(lst1)
    df.to_csv('./email.csv', sep=',', header=None, index=None)

def urlExtract():

    browser, showAll = openBrowser()

    browser.get(showAll)

    link = browser.find_elements_by_xpath("//td[@class='links cell c2 lastcol']/a")

    for g in link:
        lst2.append(g.get_attribute('href'))

    #print (lst2)
    return lst2


def diveIn():

    browser, showAll = openBrowser()

    #urllst = ['https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1376&course=4',
    #       'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1507&course=4']

    urllst = ['https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1471&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1678&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1507&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1682&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1737&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1044&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1039&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1763&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1659&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1683&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1414&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1400&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1307&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1599&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1243&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1657&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1501&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1588&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1389&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1317&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1747&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1766&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1135&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1035&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1399&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1684&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=4&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1487&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1278&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1367&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1087&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1663&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1522&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1040&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1664&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1042&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1441&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=414&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1357&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=340&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1205&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1121&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1608&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1577&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1405&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1327&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1614&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1710&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1058&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1057&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1693&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1166&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1365&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1153&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1433&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1491&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1717&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1388&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1292&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1298&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1142&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1574&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1695&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1267&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1294&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1325&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1253&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1143&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1450&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=670&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=787&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1048&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1668&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1246&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1138&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1593&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1197&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1098&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1484&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1137&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1368&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1393&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=790&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1233&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1745&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1524&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1462&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1219&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1544&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1477&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1337&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1554&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1662&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1625&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1282&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1383&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=965&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1456&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=390&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1670&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1269&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=573&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1122&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1725&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1669&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1125&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1370&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1196&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1213&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1438&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1218&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1565&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1495&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1654&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1488&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1514&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1445&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1046&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=433&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1379&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1216&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1729&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1108&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1301&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1090&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1527&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1132&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1274&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1432&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1609&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1551&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1404&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=300&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1526&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1322&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1341&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1638&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1172&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1230&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1563&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1572&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1407&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1651&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1559&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1647&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1247&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1250&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1700&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1692&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1512&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1167&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=269&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1655&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1363&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1556&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1753&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1674&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1136&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1511&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1628&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1036&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=310&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1431&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1545&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1391&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1480&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1452&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1412&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1038&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1277&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1345&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1557&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1101&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1685&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1303&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1724&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1140&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=655&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1351&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1154&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1381&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1092&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1457&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1596&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1640&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1201&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1607&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=819&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1392&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1364&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1706&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1727&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1195&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1478&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1261&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1074&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1189&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=863&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1427&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1353&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1516&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1533&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1139&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1210&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1067&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1221&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1192&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1232&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1056&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1366&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1374&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1380&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1049&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1505&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1102&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1467&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1386&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1120&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1352&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1532&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1523&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1579&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1528&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1643&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1611&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1624&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1417&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1310&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1587&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1350&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1475&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1244&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1089&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=726&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1072&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1401&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1606&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1550&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1113&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1443&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1740&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1083&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1055&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1598&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1420&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1130&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1520&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1704&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1428&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1639&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1464&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1308&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1128&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1553&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1227&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1045&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1558&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1499&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=312&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1515&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1448&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1754&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1418&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1757&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1458&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1518&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1555&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1627&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1542&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1099&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1468&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1311&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1300&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1677&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1635&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1525&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1411&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1538&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1548&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1119&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1585&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1081&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1422&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1421&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1403&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1252&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1309&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1144&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1289&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1163&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1536&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1410&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1248&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1162&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1552&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1673&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1612&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1116&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1466&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1371&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1408&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1061&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1742&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1320&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1746&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1313&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1444&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1200&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1465&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1632&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1390&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1059&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1359&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1398&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=458&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1672&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1123&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1378&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1222&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1603&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1719&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=398&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1229&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1375&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1118&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=444&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1220&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1592&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1290&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1295&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1510&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1543&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1305&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1255&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1454&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1053&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1315&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1709&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1296&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1257&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1395&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1306&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1107&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1713&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1214&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1188&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1281&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1082&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1498&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1749&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=980&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1519&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1649&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1580&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=578&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1597&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1156&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1714&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1080&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1575&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1373&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1687&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1231&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=692&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1069&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1212&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1152&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1748&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1483&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1530&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1186&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1336&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1712&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1288&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1159&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1384&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=931&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1164&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1437&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1472&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=314&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1382&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1193&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1178&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1358&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1534&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1238&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1110&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1266&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1413&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1576&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1615&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1251&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1241&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1461&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=475&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1540&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1564&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1426&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1589&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1207&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1208&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1328&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1449&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1537&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1741&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1744&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1583&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1209&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1591&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1264&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1127&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1198&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1133&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1347&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1124&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1665&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1256&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1547&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1249&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1708&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1732&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1562&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1071&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1054&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=597&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1148&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1492&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1453&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1604&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1287&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1339&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1616&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1106&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1490&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1283&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1150&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1535&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1620&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1734&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1521&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1435&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1237&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1346&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1338&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1394&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1500&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1117&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1194&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1149&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1329&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1493&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1590&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1342&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1451&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1095&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1750&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1636&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1680&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1078&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=359&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1223&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1076&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1145&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1158&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1707&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1204&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1696&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1502&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1184&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1621&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1170&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1629&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1705&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1716&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1396&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1109&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1739&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1316&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1245&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1191&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1181&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1694&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=392&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1312&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1275&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1509&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1085&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1299&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1280&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1686&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1103&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1263&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1602&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1442&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1508&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1372&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1569&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1578&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=308&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1333&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1660&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1169&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1702&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1126&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1722&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1285&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1157&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=939&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1642&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1434&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1284&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1064&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1354&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1168&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1646&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1187&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1304&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1254&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1406&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1387&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1286&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1273&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1171&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1560&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1721&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1075&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1276&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1486&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1656&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=820&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1425&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1065&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1671&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1093&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1211&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1463&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1650&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1070&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1344&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1637&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1180&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1436&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1177&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1513&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1568&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1377&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1190&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1600&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1703&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=763&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1691&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1097&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=607&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1644&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1613&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1155&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1376&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1756&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=996&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1279&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1259&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1485&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1318&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1314&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=318&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1541&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1504&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1176&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1115&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1356&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1236&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1199&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1549&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1348&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1743&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1165&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1718&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1369&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1146&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1573&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1041&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1439&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1179&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1567&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1503&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1489&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1051&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1262&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1666&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1100&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=616&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1735&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1470&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1111&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1460&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1105&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1349&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1160&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1531&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1728&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1234&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1715&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1755&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1063&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1626&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1302&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1173&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1481&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1697&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1385&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1091&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1424&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1323&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1641&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1681&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1052&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1335&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1331&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1077&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1112&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1265&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1319&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1161&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1423&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1260&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1736&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=728&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1175&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1332&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1397&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1096&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1326&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1731&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1517&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1183&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=307&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1415&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1633&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1630&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1738&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1272&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1645&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1202&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1529&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1479&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1752&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1235&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1094&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1334&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=339&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1419&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1605&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1482&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1297&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1104&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1581&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1360&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1225&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1088&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1676&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=89&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=749&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1226&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1688&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1594&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1459&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1268&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1751&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1582&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1497&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1215&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1340&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1623&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1546&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1570&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1648&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1619&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1446&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1079&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1571&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1217&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1066&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1131&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1174&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1409&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1271&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1151&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1661&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1679&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1723&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1689&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1293&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1631&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1355&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1343&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=928&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1675&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1361&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1566&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1595&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1402&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1073&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1240&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=60&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=29&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1720&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1185&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1362&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=94&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1561&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1618&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1239&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1141&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1653&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1617&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1586&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1584&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=37&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1429&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1494&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1765&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1129&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=794&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=793&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1416&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1270&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1206&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1506&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1086&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1767&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1764&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1047&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=2394&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1258&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=272&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1447&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1114&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1610&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1324&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1711&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1733&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1474&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1469&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1652&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1134&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1060&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1224&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=79&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1182&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=95&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1440&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1228&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1826&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1068&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=317&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1701&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1699&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1698&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1084&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=1043&course=4',
              'https://mitsloan.onlinecampus.getsmarter.com/user/view.php?id=306&course=4']

    masterlst = []

    for i in range(0,len(urllst)):
        print(urllst[i])
        browser.get(urllst[i])

        name = browser.find_elements_by_xpath("//div[@class='page-header-headings']/h2")
        body = browser.find_elements_by_class_name("no-overflow")
        restofthem = browser.find_elements_by_xpath("//li[@class='contentnode'][1 <= position() and position() < 7]/dl/dd")

        temp1=[]
        for a, b in zip(name,body):
            temp1.extend([a.text,b.text])

        temp2 = []
        for t in restofthem:
            temp2.append(t.text)

        masterlst.append(temp1+temp2)

    #browser.quit()
    #print (masterlst)
        df = pd.DataFrame(masterlst)
        df.to_csv('./student.csv', sep=',', header=None, index=None)

    return

def combineCsv():

    df1 = pd.read_csv('./email.csv')
    df2 = pd.read_csv('./student.csv')
    finaloutput = df1.join(df2, on='name', how='left',lsuffix='_left', rsuffix='_right')
    finaloutput.to_csv('./CSAIL_contact.csv', sep=',', header=None, index=None)



if __name__ == '__main__':

    #urlExtract()
    #diveIn()
    #profileSum()
    combineCsv()

